name: String Validation
description: Validate multiple action outputs, environment variables, and strings in a single step
author: Jonathan Reyes
inputs:
  validations:
    required: true
    description: An array of settings
outputs:
  errors:
    description: Errors if something in the PR validation did not pass
  errorMessage:
    description: Returns a markdown list of errors
runs:
  using: node16
  main: dist/index.js
