name: String Validation
description: Validate multiple action outputs, environment variables, and strings in a single step
author: Jonathan Reyes
inputs:
  fail_on_error:
    description: Fail the step if an error is detected
  validations:
    required: true
    description: An array of settings
outputs:
  status:
    description: (pass|fail) in relation to validations
  errors:
    description: Errors if something in the PR validation did not pass
  errorMessage:
    description: Returns a markdown list of errors
runs:
  using: node16
  main: dist/index.js
