name: Pull Request Validation
description: Validate your pull requests with configurable checks
author: Jonathan Reyes
inputs:
  config:
    required: true
    description: JSON configuration for tests
outputs:
  errors:
    description: Errors if something in the PR validation did not pass
runs:
  using: node16
  main: dist/index.js
